[2023-12-30T00:29:05.638+0000] {processor.py:157} INFO - Started process (PID=521) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T00:29:05.639+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T00:29:05.642+0000] {logging_mixin.py:154} INFO - [2023-12-30T00:29:05.641+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T00:29:05.647+0000] {logging_mixin.py:154} INFO - [2023-12-30T00:29:05.646+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T00:29:05.647+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T00:29:05.661+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.026 seconds
[2023-12-30T00:47:13.117+0000] {processor.py:157} INFO - Started process (PID=529) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T00:47:13.118+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T00:47:13.123+0000] {logging_mixin.py:154} INFO - [2023-12-30T00:47:13.122+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T00:47:13.130+0000] {logging_mixin.py:154} INFO - [2023-12-30T00:47:13.128+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T00:47:13.131+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T00:47:13.153+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.040 seconds
[2023-12-30T01:19:25.159+0000] {processor.py:157} INFO - Started process (PID=537) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T01:19:25.159+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T01:19:25.163+0000] {logging_mixin.py:154} INFO - [2023-12-30T01:19:25.163+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T01:19:25.169+0000] {logging_mixin.py:154} INFO - [2023-12-30T01:19:25.168+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T01:19:25.170+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T01:19:25.183+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.027 seconds
[2023-12-30T01:36:49.407+0000] {processor.py:157} INFO - Started process (PID=545) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T01:36:49.408+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T01:36:49.412+0000] {logging_mixin.py:154} INFO - [2023-12-30T01:36:49.411+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T01:36:49.419+0000] {logging_mixin.py:154} INFO - [2023-12-30T01:36:49.417+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T01:36:49.419+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T01:36:49.441+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.038 seconds
[2023-12-30T01:54:00.705+0000] {processor.py:157} INFO - Started process (PID=553) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T01:54:00.706+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T01:54:00.709+0000] {logging_mixin.py:154} INFO - [2023-12-30T01:54:00.709+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T01:54:00.715+0000] {logging_mixin.py:154} INFO - [2023-12-30T01:54:00.713+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T01:54:00.715+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T01:54:00.731+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.031 seconds
[2023-12-30T02:26:58.945+0000] {processor.py:157} INFO - Started process (PID=561) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T02:26:58.947+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T02:26:58.950+0000] {logging_mixin.py:154} INFO - [2023-12-30T02:26:58.950+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T02:26:58.958+0000] {logging_mixin.py:154} INFO - [2023-12-30T02:26:58.956+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T02:26:58.959+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T02:26:58.981+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.039 seconds
[2023-12-30T02:45:03.129+0000] {processor.py:157} INFO - Started process (PID=569) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T02:45:03.131+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T02:45:03.135+0000] {logging_mixin.py:154} INFO - [2023-12-30T02:45:03.135+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T02:45:03.145+0000] {logging_mixin.py:154} INFO - [2023-12-30T02:45:03.142+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T02:45:03.145+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T02:45:03.164+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.046 seconds
[2023-12-30T03:01:54.400+0000] {processor.py:157} INFO - Started process (PID=577) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T03:01:54.401+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T03:01:54.406+0000] {logging_mixin.py:154} INFO - [2023-12-30T03:01:54.406+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T03:01:54.414+0000] {logging_mixin.py:154} INFO - [2023-12-30T03:01:54.412+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T03:01:54.415+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T03:01:54.439+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2023-12-30T03:32:35.578+0000] {processor.py:157} INFO - Started process (PID=585) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T03:32:35.580+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T03:32:35.584+0000] {logging_mixin.py:154} INFO - [2023-12-30T03:32:35.583+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T03:32:35.592+0000] {logging_mixin.py:154} INFO - [2023-12-30T03:32:35.590+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T03:32:35.593+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T03:32:35.612+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.040 seconds
[2023-12-30T03:49:11.038+0000] {processor.py:157} INFO - Started process (PID=593) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T03:49:11.044+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T03:49:11.051+0000] {logging_mixin.py:154} INFO - [2023-12-30T03:49:11.051+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T03:49:11.057+0000] {logging_mixin.py:154} INFO - [2023-12-30T03:49:11.056+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T03:49:11.058+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T03:49:11.072+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.038 seconds
[2023-12-30T04:04:58.289+0000] {processor.py:157} INFO - Started process (PID=601) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T04:04:58.290+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T04:04:58.293+0000] {logging_mixin.py:154} INFO - [2023-12-30T04:04:58.293+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T04:04:58.301+0000] {logging_mixin.py:154} INFO - [2023-12-30T04:04:58.299+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T04:04:58.301+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T04:04:58.322+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.040 seconds
[2023-12-30T04:38:04.452+0000] {processor.py:157} INFO - Started process (PID=609) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T04:38:04.455+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T04:38:04.464+0000] {logging_mixin.py:154} INFO - [2023-12-30T04:38:04.462+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T04:38:04.471+0000] {logging_mixin.py:154} INFO - [2023-12-30T04:38:04.470+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T04:38:04.472+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T04:38:04.490+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.043 seconds
[2023-12-30T04:55:56.706+0000] {processor.py:157} INFO - Started process (PID=617) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T04:55:56.707+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T04:55:56.713+0000] {logging_mixin.py:154} INFO - [2023-12-30T04:55:56.712+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T04:55:56.722+0000] {logging_mixin.py:154} INFO - [2023-12-30T04:55:56.720+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T04:55:56.723+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T04:55:56.754+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.054 seconds
[2023-12-30T05:12:26.022+0000] {processor.py:157} INFO - Started process (PID=625) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T05:12:26.025+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T05:12:26.034+0000] {logging_mixin.py:154} INFO - [2023-12-30T05:12:26.034+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T05:12:26.046+0000] {logging_mixin.py:154} INFO - [2023-12-30T05:12:26.044+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T05:12:26.047+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T05:12:26.070+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.058 seconds
[2023-12-30T05:45:43.147+0000] {processor.py:157} INFO - Started process (PID=633) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T05:45:43.149+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T05:45:43.158+0000] {logging_mixin.py:154} INFO - [2023-12-30T05:45:43.157+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T05:45:43.166+0000] {logging_mixin.py:154} INFO - [2023-12-30T05:45:43.164+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T05:45:43.167+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T05:45:43.190+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.054 seconds
[2023-12-30T06:01:40.574+0000] {processor.py:157} INFO - Started process (PID=641) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T06:01:40.575+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T06:01:40.593+0000] {logging_mixin.py:154} INFO - [2023-12-30T06:01:40.591+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T06:01:40.613+0000] {logging_mixin.py:154} INFO - [2023-12-30T06:01:40.610+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T06:01:40.614+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T06:01:40.635+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.066 seconds
[2023-12-30T06:32:26.761+0000] {processor.py:157} INFO - Started process (PID=649) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T06:32:26.763+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T06:32:26.766+0000] {logging_mixin.py:154} INFO - [2023-12-30T06:32:26.766+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T06:32:26.774+0000] {logging_mixin.py:154} INFO - [2023-12-30T06:32:26.773+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T06:32:26.775+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T06:32:26.796+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.043 seconds
[2023-12-30T06:48:29.136+0000] {processor.py:157} INFO - Started process (PID=657) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T06:48:29.138+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T06:48:29.150+0000] {logging_mixin.py:154} INFO - [2023-12-30T06:48:29.149+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T06:48:29.169+0000] {logging_mixin.py:154} INFO - [2023-12-30T06:48:29.166+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T06:48:29.170+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T06:48:29.191+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.064 seconds
[2023-12-30T06:58:53.476+0000] {processor.py:157} INFO - Started process (PID=665) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T06:58:53.478+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T06:58:53.493+0000] {logging_mixin.py:154} INFO - [2023-12-30T06:58:53.491+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T06:58:53.509+0000] {logging_mixin.py:154} INFO - [2023-12-30T06:58:53.507+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T06:58:53.510+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T06:58:53.531+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.069 seconds
[2023-12-30T07:33:18.552+0000] {processor.py:157} INFO - Started process (PID=673) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T07:33:18.553+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T07:33:18.556+0000] {logging_mixin.py:154} INFO - [2023-12-30T07:33:18.555+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T07:33:18.578+0000] {logging_mixin.py:154} INFO - [2023-12-30T07:33:18.576+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T07:33:18.578+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T07:33:18.592+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.043 seconds
[2023-12-30T07:50:51.040+0000] {processor.py:157} INFO - Started process (PID=681) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T07:50:51.041+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T07:50:51.045+0000] {logging_mixin.py:154} INFO - [2023-12-30T07:50:51.045+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T07:50:51.053+0000] {logging_mixin.py:154} INFO - [2023-12-30T07:50:51.051+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T07:50:51.054+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T07:50:51.078+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.044 seconds
[2023-12-30T08:07:59.472+0000] {processor.py:157} INFO - Started process (PID=689) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T08:07:59.473+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T08:07:59.475+0000] {logging_mixin.py:154} INFO - [2023-12-30T08:07:59.475+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T08:07:59.480+0000] {logging_mixin.py:154} INFO - [2023-12-30T08:07:59.479+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T08:07:59.481+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T08:07:59.491+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.022 seconds
[2023-12-30T08:42:52.953+0000] {processor.py:157} INFO - Started process (PID=697) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T08:42:52.954+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T08:42:52.958+0000] {logging_mixin.py:154} INFO - [2023-12-30T08:42:52.957+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T08:42:52.967+0000] {logging_mixin.py:154} INFO - [2023-12-30T08:42:52.963+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T08:42:52.968+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T08:42:52.989+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.040 seconds
[2023-12-30T08:59:49.387+0000] {processor.py:157} INFO - Started process (PID=705) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T08:59:49.388+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T08:59:49.393+0000] {logging_mixin.py:154} INFO - [2023-12-30T08:59:49.392+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T08:59:49.400+0000] {logging_mixin.py:154} INFO - [2023-12-30T08:59:49.398+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T08:59:49.401+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T08:59:49.423+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2023-12-30T09:17:35.812+0000] {processor.py:157} INFO - Started process (PID=713) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T09:17:35.813+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T09:17:35.817+0000] {logging_mixin.py:154} INFO - [2023-12-30T09:17:35.817+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T09:17:35.822+0000] {logging_mixin.py:154} INFO - [2023-12-30T09:17:35.821+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T09:17:35.823+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T09:17:35.834+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.026 seconds
[2023-12-30T09:53:46.985+0000] {processor.py:157} INFO - Started process (PID=721) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T09:53:46.987+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T09:53:46.994+0000] {logging_mixin.py:154} INFO - [2023-12-30T09:53:46.993+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T09:53:47.002+0000] {logging_mixin.py:154} INFO - [2023-12-30T09:53:47.000+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T09:53:47.003+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T09:53:47.023+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.048 seconds
[2023-12-30T10:11:12.316+0000] {processor.py:157} INFO - Started process (PID=729) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T10:11:12.316+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T10:11:12.319+0000] {logging_mixin.py:154} INFO - [2023-12-30T10:11:12.319+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T10:11:12.324+0000] {logging_mixin.py:154} INFO - [2023-12-30T10:11:12.322+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T10:11:12.324+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T10:11:12.338+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.026 seconds
[2023-12-30T11:16:32.765+0000] {processor.py:157} INFO - Started process (PID=737) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T11:16:32.766+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T11:16:32.770+0000] {logging_mixin.py:154} INFO - [2023-12-30T11:16:32.770+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T11:16:32.778+0000] {logging_mixin.py:154} INFO - [2023-12-30T11:16:32.776+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T11:16:32.779+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T11:16:32.808+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.049 seconds
[2023-12-30T12:32:39.125+0000] {processor.py:157} INFO - Started process (PID=745) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T12:32:39.126+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T12:32:39.128+0000] {logging_mixin.py:154} INFO - [2023-12-30T12:32:39.128+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T12:32:39.133+0000] {logging_mixin.py:154} INFO - [2023-12-30T12:32:39.132+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T12:32:39.134+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T12:32:39.149+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.027 seconds
[2023-12-30T13:11:10.828+0000] {processor.py:157} INFO - Started process (PID=753) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T13:11:10.831+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T13:11:10.837+0000] {logging_mixin.py:154} INFO - [2023-12-30T13:11:10.836+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T13:11:10.847+0000] {logging_mixin.py:154} INFO - [2023-12-30T13:11:10.845+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T13:11:10.848+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T13:11:10.868+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.048 seconds
[2023-12-30T13:44:43.871+0000] {processor.py:157} INFO - Started process (PID=760) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T13:44:43.873+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T13:44:43.884+0000] {logging_mixin.py:154} INFO - [2023-12-30T13:44:43.883+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T13:44:43.891+0000] {logging_mixin.py:154} INFO - [2023-12-30T13:44:43.889+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T13:44:43.891+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T13:44:43.908+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2023-12-30T14:54:08.086+0000] {processor.py:157} INFO - Started process (PID=768) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T14:54:08.087+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T14:54:08.092+0000] {logging_mixin.py:154} INFO - [2023-12-30T14:54:08.092+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T14:54:08.104+0000] {logging_mixin.py:154} INFO - [2023-12-30T14:54:08.102+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T14:54:08.105+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T14:54:08.129+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.048 seconds
[2023-12-30T15:28:14.041+0000] {processor.py:157} INFO - Started process (PID=776) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T15:28:14.042+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T15:28:14.046+0000] {logging_mixin.py:154} INFO - [2023-12-30T15:28:14.045+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T15:28:14.052+0000] {logging_mixin.py:154} INFO - [2023-12-30T15:28:14.051+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T15:28:14.053+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T15:28:14.069+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.033 seconds
[2023-12-30T15:55:06.298+0000] {processor.py:157} INFO - Started process (PID=784) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T15:55:06.300+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T15:55:06.308+0000] {logging_mixin.py:154} INFO - [2023-12-30T15:55:06.307+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T15:55:06.319+0000] {logging_mixin.py:154} INFO - [2023-12-30T15:55:06.317+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T15:55:06.320+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T15:55:06.340+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.049 seconds
[2023-12-30T17:12:05.358+0000] {processor.py:157} INFO - Started process (PID=792) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T17:12:05.359+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T17:12:05.363+0000] {logging_mixin.py:154} INFO - [2023-12-30T17:12:05.362+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T17:12:05.384+0000] {logging_mixin.py:154} INFO - [2023-12-30T17:12:05.383+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T17:12:05.385+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T17:12:05.411+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.057 seconds
[2023-12-30T17:46:13.382+0000] {processor.py:157} INFO - Started process (PID=800) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T17:46:13.383+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T17:46:13.387+0000] {logging_mixin.py:154} INFO - [2023-12-30T17:46:13.387+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T17:46:13.394+0000] {logging_mixin.py:154} INFO - [2023-12-30T17:46:13.392+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T17:46:13.394+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T17:46:13.413+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.036 seconds
[2023-12-30T18:20:34.216+0000] {processor.py:157} INFO - Started process (PID=808) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T18:20:34.218+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T18:20:34.234+0000] {logging_mixin.py:154} INFO - [2023-12-30T18:20:34.232+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T18:20:34.280+0000] {logging_mixin.py:154} INFO - [2023-12-30T18:20:34.275+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T18:20:34.280+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T18:20:34.325+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.121 seconds
[2023-12-30T18:21:04.637+0000] {processor.py:157} INFO - Started process (PID=816) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T18:21:04.640+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T18:21:04.645+0000] {logging_mixin.py:154} INFO - [2023-12-30T18:21:04.644+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T18:21:04.654+0000] {logging_mixin.py:154} INFO - [2023-12-30T18:21:04.652+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T18:21:04.655+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T18:21:04.678+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.049 seconds
[2023-12-30T19:40:28.948+0000] {processor.py:157} INFO - Started process (PID=824) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T19:40:28.949+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T19:40:28.952+0000] {logging_mixin.py:154} INFO - [2023-12-30T19:40:28.951+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T19:40:28.957+0000] {logging_mixin.py:154} INFO - [2023-12-30T19:40:28.956+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T19:40:28.958+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T19:40:28.973+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.031 seconds
[2023-12-30T20:19:46.478+0000] {processor.py:157} INFO - Started process (PID=832) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T20:19:46.480+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T20:19:46.484+0000] {logging_mixin.py:154} INFO - [2023-12-30T20:19:46.483+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T20:19:46.491+0000] {logging_mixin.py:154} INFO - [2023-12-30T20:19:46.489+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T20:19:46.491+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T20:19:46.510+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.035 seconds
[2023-12-30T21:39:28.406+0000] {processor.py:157} INFO - Started process (PID=840) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T21:39:28.408+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T21:39:28.411+0000] {logging_mixin.py:154} INFO - [2023-12-30T21:39:28.411+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T21:39:28.418+0000] {logging_mixin.py:154} INFO - [2023-12-30T21:39:28.416+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T21:39:28.418+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T21:39:28.445+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.043 seconds
[2023-12-30T23:21:17.430+0000] {processor.py:157} INFO - Started process (PID=848) to work on /opt/airflow/dags/test_dag.py
[2023-12-30T23:21:17.432+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-30T23:21:17.437+0000] {logging_mixin.py:154} INFO - [2023-12-30T23:21:17.437+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-30T23:21:17.453+0000] {logging_mixin.py:154} INFO - [2023-12-30T23:21:17.450+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-30T23:21:17.454+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-30T23:21:17.477+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.054 seconds
