[2024-01-26T19:48:20.865+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_dag.test_redshift manual__2024-01-26T19:48:19.763219+00:00 [queued]>
[2024-01-26T19:48:20.869+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_dag.test_redshift manual__2024-01-26T19:48:19.763219+00:00 [queued]>
[2024-01-26T19:48:20.869+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-26T19:48:20.875+0000] {taskinstance.py:1382} INFO - Executing <Task(RedshiftDataOperator): test_redshift> on 2024-01-26 19:48:19.763219+00:00
[2024-01-26T19:48:20.878+0000] {standard_task_runner.py:57} INFO - Started process 1277 to run task
[2024-01-26T19:48:20.881+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'test_dag', 'test_redshift', 'manual__2024-01-26T19:48:19.763219+00:00', '--job-id', '385', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmp640lan6d']
[2024-01-26T19:48:20.881+0000] {standard_task_runner.py:85} INFO - Job 385: Subtask test_redshift
[2024-01-26T19:48:20.909+0000] {task_command.py:416} INFO - Running <TaskInstance: test_dag.test_redshift manual__2024-01-26T19:48:19.763219+00:00 [running]> on host d6d47e6adee9
[2024-01-26T19:48:20.949+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_dag' AIRFLOW_CTX_TASK_ID='test_redshift' AIRFLOW_CTX_EXECUTION_DATE='2024-01-26T19:48:19.763219+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-26T19:48:19.763219+00:00'
[2024-01-26T19:48:20.949+0000] {redshift_data.py:122} INFO - Executing statement: 
                select *
                from marina.applicant a 
                limit 10; 
                
[2024-01-26T19:48:20.954+0000] {base.py:73} INFO - Using connection ID 'redshift_default' for task execution.
[2024-01-26T19:48:20.954+0000] {warnings.py:109} WARNING - <string>:9: UserWarning: AWS Connection (conn_id='redshift_default', conn_type='redshift') expected connection type 'aws', got 'redshift'. This connection might not work correctly. Please use Amazon Web Services Connection type.

[2024-01-26T19:48:20.955+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='redshift_default', conn_type='redshift') credentials retrieved from login and password.
[2024-01-26T19:48:20.955+0000] {warnings.py:109} WARNING - <string>:9: AirflowProviderDeprecationWarning: Host marina-dev.cokvj8a8m59a.us-west-2.redshift.amazonaws.com specified in the connection is not used. Please, set it on extra['endpoint_url'] instead

[2024-01-26T19:48:21.659+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/operators/redshift_data.py", line 124, in execute
    self.statement_id = self.hook.execute_query(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 99, in execute_query
    resp = self.conn.execute_statement(**trim_none_values(kwargs))
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (UnrecognizedClientException) when calling the ExecuteStatement operation: The security token included in the request is invalid.
[2024-01-26T19:48:21.679+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=test_dag, task_id=test_redshift, execution_date=20240126T194819, start_date=20240126T194820, end_date=20240126T194821
[2024-01-26T19:48:21.688+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 385 for task test_redshift (An error occurred (UnrecognizedClientException) when calling the ExecuteStatement operation: The security token included in the request is invalid.; 1277)
[2024-01-26T19:48:21.731+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-26T19:48:21.746+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
