[2024-01-31T17:12:37.523+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: your_redshift_dag.run_redshift_query scheduled__2023-08-29T00:00:00+00:00 [queued]>
[2024-01-31T17:12:37.530+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: your_redshift_dag.run_redshift_query scheduled__2023-08-29T00:00:00+00:00 [queued]>
[2024-01-31T17:12:37.531+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2024-01-31T17:12:37.539+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): run_redshift_query> on 2023-08-29 00:00:00+00:00
[2024-01-31T17:12:37.544+0000] {standard_task_runner.py:57} INFO - Started process 10742 to run task
[2024-01-31T17:12:37.549+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'your_redshift_dag', 'run_redshift_query', 'scheduled__2023-08-29T00:00:00+00:00', '--job-id', '893', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpbek65oxy']
[2024-01-31T17:12:37.552+0000] {standard_task_runner.py:85} INFO - Job 893: Subtask run_redshift_query
[2024-01-31T17:12:37.614+0000] {task_command.py:416} INFO - Running <TaskInstance: your_redshift_dag.run_redshift_query scheduled__2023-08-29T00:00:00+00:00 [running]> on host d6d47e6adee9
[2024-01-31T17:12:37.693+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_owner' AIRFLOW_CTX_DAG_ID='your_redshift_dag' AIRFLOW_CTX_TASK_ID='run_redshift_query' AIRFLOW_CTX_EXECUTION_DATE='2023-08-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-29T00:00:00+00:00'
[2024-01-31T17:12:38.248+0000] {base.py:73} INFO - Using connection ID 'redshift_conn' for task execution.
[2024-01-31T17:12:38.249+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_dag.py", line 30, in execute_redshift_query
    result = hook.get_pandas_df(sql=redshift_query)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 218, in get_pandas_df
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 155, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "marina-dev.cokvj8a8m59a.us-west-2.redshift.amazonaws.com:5439" to address: Name or service not known

[2024-01-31T17:12:38.256+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=your_redshift_dag, task_id=run_redshift_query, execution_date=20230829T000000, start_date=20240131T171237, end_date=20240131T171238
[2024-01-31T17:12:38.263+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 893 for task run_redshift_query (could not translate host name "marina-dev.cokvj8a8m59a.us-west-2.redshift.amazonaws.com:5439" to address: Name or service not known
; 10742)
[2024-01-31T17:12:38.291+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-31T17:12:38.302+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
