[2024-01-31T00:00:00.687+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_dag.test_redshift scheduled__2024-01-30T00:00:00+00:00 [queued]>
[2024-01-31T00:00:00.692+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_dag.test_redshift scheduled__2024-01-30T00:00:00+00:00 [queued]>
[2024-01-31T00:00:00.693+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-31T00:00:00.700+0000] {taskinstance.py:1382} INFO - Executing <Task(RedshiftDataOperator): test_redshift> on 2024-01-30 00:00:00+00:00
[2024-01-31T00:00:00.704+0000] {standard_task_runner.py:57} INFO - Started process 93243 to run task
[2024-01-31T00:00:00.707+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'test_dag', 'test_redshift', 'scheduled__2024-01-30T00:00:00+00:00', '--job-id', '394', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpgptttf7y']
[2024-01-31T00:00:00.707+0000] {standard_task_runner.py:85} INFO - Job 394: Subtask test_redshift
[2024-01-31T00:00:00.739+0000] {task_command.py:416} INFO - Running <TaskInstance: test_dag.test_redshift scheduled__2024-01-30T00:00:00+00:00 [running]> on host d6d47e6adee9
[2024-01-31T00:00:00.782+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_dag' AIRFLOW_CTX_TASK_ID='test_redshift' AIRFLOW_CTX_EXECUTION_DATE='2024-01-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-30T00:00:00+00:00'
[2024-01-31T00:00:00.783+0000] {redshift_data.py:122} INFO - Executing statement: 
                select *
                from marina.applicant a 
                limit 10; 
                
[2024-01-31T00:00:00.788+0000] {base.py:73} INFO - Using connection ID 'aws_default' for task execution.
[2024-01-31T00:00:00.788+0000] {warnings.py:109} WARNING - <string>:9: UserWarning: AWS Connection (conn_id='aws_default', conn_type='redshift') expected connection type 'aws', got 'redshift'. This connection might not work correctly. Please use Amazon Web Services Connection type.

[2024-01-31T00:00:00.789+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_default', conn_type='redshift') credentials retrieved from login and password.
[2024-01-31T00:00:00.789+0000] {warnings.py:109} WARNING - <string>:9: AirflowProviderDeprecationWarning: Host marina-dev.cokvj8a8m59a.us-west-2.redshift.amazonaws.com specified in the connection is not used. Please, set it on extra['endpoint_url'] instead

[2024-01-31T00:00:01.576+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/operators/redshift_data.py", line 124, in execute
    self.statement_id = self.hook.execute_query(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 99, in execute_query
    resp = self.conn.execute_statement(**trim_none_values(kwargs))
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (UnrecognizedClientException) when calling the ExecuteStatement operation: The security token included in the request is invalid.
[2024-01-31T00:00:01.589+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=test_dag, task_id=test_redshift, execution_date=20240130T000000, start_date=20240131T000000, end_date=20240131T000001
[2024-01-31T00:00:01.599+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 394 for task test_redshift (An error occurred (UnrecognizedClientException) when calling the ExecuteStatement operation: The security token included in the request is invalid.; 93243)
[2024-01-31T00:00:01.623+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-31T00:00:01.639+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
