[2023-12-29T20:42:48.645+0000] {processor.py:157} INFO - Started process (PID=106) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T20:42:48.646+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T20:42:48.650+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:42:48.649+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T20:42:48.658+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:42:48.655+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T20:42:48.658+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T20:42:48.675+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.033 seconds
[2023-12-29T20:43:18.965+0000] {processor.py:157} INFO - Started process (PID=114) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T20:43:18.967+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T20:43:18.973+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:43:18.972+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T20:43:18.979+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:43:18.978+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T20:43:18.980+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T20:43:18.998+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.041 seconds
[2023-12-29T20:43:49.281+0000] {processor.py:157} INFO - Started process (PID=122) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T20:43:49.282+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T20:43:49.284+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:43:49.284+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T20:43:49.288+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:43:49.287+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T20:43:49.289+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T20:43:49.301+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.023 seconds
[2023-12-29T20:44:19.597+0000] {processor.py:157} INFO - Started process (PID=130) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T20:44:19.598+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T20:44:19.601+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:44:19.601+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T20:44:19.607+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:44:19.606+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T20:44:19.608+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T20:44:19.623+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.030 seconds
[2023-12-29T20:44:49.929+0000] {processor.py:157} INFO - Started process (PID=138) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T20:44:49.930+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T20:44:49.933+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:44:49.933+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T20:44:49.939+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:44:49.938+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T20:44:49.939+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T20:44:49.956+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.030 seconds
[2023-12-29T20:45:20.258+0000] {processor.py:157} INFO - Started process (PID=146) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T20:45:20.259+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T20:45:20.261+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:45:20.261+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T20:45:20.269+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:45:20.267+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T20:45:20.269+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T20:45:20.297+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.043 seconds
[2023-12-29T20:45:50.569+0000] {processor.py:157} INFO - Started process (PID=154) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T20:45:50.570+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T20:45:50.580+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:45:50.580+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T20:45:50.593+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:45:50.586+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T20:45:50.593+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T20:45:50.611+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.045 seconds
[2023-12-29T20:46:20.941+0000] {processor.py:157} INFO - Started process (PID=162) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T20:46:20.942+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T20:46:20.946+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:46:20.945+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T20:46:20.958+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:46:20.956+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T20:46:20.959+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T20:46:20.976+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.040 seconds
[2023-12-29T20:46:51.303+0000] {processor.py:157} INFO - Started process (PID=170) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T20:46:51.304+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T20:46:51.308+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:46:51.308+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T20:46:51.320+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:46:51.317+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T20:46:51.321+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T20:46:51.346+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.047 seconds
[2023-12-29T20:47:21.628+0000] {processor.py:157} INFO - Started process (PID=178) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T20:47:21.629+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T20:47:21.631+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:47:21.631+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T20:47:21.639+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:47:21.638+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T20:47:21.640+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T20:47:21.655+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.031 seconds
[2023-12-29T20:47:52.002+0000] {processor.py:157} INFO - Started process (PID=186) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T20:47:52.003+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T20:47:52.007+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:47:52.006+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T20:47:52.017+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:47:52.016+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T20:47:52.018+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T20:47:52.035+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.037 seconds
[2023-12-29T20:48:22.361+0000] {processor.py:157} INFO - Started process (PID=194) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T20:48:22.363+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T20:48:22.366+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:48:22.366+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T20:48:22.373+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:48:22.372+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T20:48:22.374+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T20:48:22.400+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.045 seconds
[2023-12-29T20:48:52.745+0000] {processor.py:157} INFO - Started process (PID=202) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T20:48:52.747+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T20:48:52.751+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:48:52.751+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T20:48:52.765+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:48:52.760+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T20:48:52.765+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T20:48:52.783+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.044 seconds
[2023-12-29T20:49:23.076+0000] {processor.py:157} INFO - Started process (PID=210) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T20:49:23.077+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T20:49:23.079+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:49:23.078+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T20:49:23.086+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:49:23.084+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T20:49:23.086+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T20:49:23.104+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.031 seconds
[2023-12-29T20:49:53.461+0000] {processor.py:157} INFO - Started process (PID=217) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T20:49:53.462+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T20:49:53.467+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:49:53.467+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T20:49:53.478+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:49:53.476+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T20:49:53.479+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T20:49:53.498+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2023-12-29T20:50:23.820+0000] {processor.py:157} INFO - Started process (PID=225) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T20:50:23.821+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T20:50:23.827+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:50:23.826+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T20:50:23.837+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:50:23.834+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T20:50:23.837+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T20:50:23.860+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.047 seconds
[2023-12-29T20:50:54.116+0000] {processor.py:157} INFO - Started process (PID=233) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T20:50:54.117+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T20:50:54.120+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:50:54.119+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T20:50:54.124+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:50:54.123+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T20:50:54.124+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T20:50:54.141+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.028 seconds
[2023-12-29T20:51:24.528+0000] {processor.py:157} INFO - Started process (PID=241) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T20:51:24.529+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T20:51:24.535+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:51:24.534+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T20:51:24.544+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:51:24.542+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T20:51:24.545+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T20:51:24.567+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.044 seconds
[2023-12-29T20:51:54.836+0000] {processor.py:157} INFO - Started process (PID=249) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T20:51:54.837+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T20:51:54.839+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:51:54.839+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T20:51:54.844+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:51:54.842+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T20:51:54.844+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T20:51:54.857+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.024 seconds
[2023-12-29T20:52:25.223+0000] {processor.py:157} INFO - Started process (PID=257) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T20:52:25.225+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T20:52:25.228+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:52:25.228+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T20:52:25.234+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:52:25.233+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T20:52:25.234+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T20:52:25.251+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.032 seconds
[2023-12-29T20:52:55.651+0000] {processor.py:157} INFO - Started process (PID=265) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T20:52:55.652+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T20:52:55.657+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:52:55.656+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T20:52:55.666+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:52:55.664+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T20:52:55.667+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T20:52:55.689+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2023-12-29T20:53:26.034+0000] {processor.py:157} INFO - Started process (PID=273) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T20:53:26.036+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T20:53:26.041+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:53:26.041+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T20:53:26.053+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:53:26.050+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T20:53:26.054+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T20:53:26.073+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.044 seconds
[2023-12-29T20:53:56.471+0000] {processor.py:157} INFO - Started process (PID=281) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T20:53:56.472+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T20:53:56.477+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:53:56.476+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T20:53:56.484+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:53:56.482+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T20:53:56.484+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T20:53:56.500+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.036 seconds
[2023-12-29T20:54:26.793+0000] {processor.py:157} INFO - Started process (PID=289) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T20:54:26.795+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T20:54:26.798+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:54:26.798+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T20:54:26.804+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:54:26.803+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T20:54:26.805+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T20:54:26.818+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.031 seconds
[2023-12-29T20:54:57.050+0000] {processor.py:157} INFO - Started process (PID=297) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T20:54:57.051+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T20:54:57.054+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:54:57.053+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T20:54:57.061+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:54:57.060+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T20:54:57.062+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T20:54:57.075+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.027 seconds
[2023-12-29T20:55:27.355+0000] {processor.py:157} INFO - Started process (PID=305) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T20:55:27.356+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T20:55:27.358+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:55:27.357+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T20:55:27.361+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:55:27.360+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T20:55:27.362+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T20:55:27.373+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.021 seconds
[2023-12-29T20:55:57.694+0000] {processor.py:157} INFO - Started process (PID=313) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T20:55:57.699+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T20:55:57.703+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:55:57.702+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T20:55:57.717+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:55:57.715+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T20:55:57.718+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T20:55:57.735+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.045 seconds
[2023-12-29T20:56:28.099+0000] {processor.py:157} INFO - Started process (PID=321) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T20:56:28.101+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T20:56:28.105+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:56:28.105+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T20:56:28.114+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:56:28.110+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T20:56:28.115+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T20:56:28.137+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.043 seconds
[2023-12-29T20:56:58.543+0000] {processor.py:157} INFO - Started process (PID=329) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T20:56:58.544+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T20:56:58.548+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:56:58.547+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T20:56:58.552+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:56:58.551+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T20:56:58.553+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T20:56:58.576+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.038 seconds
[2023-12-29T20:57:28.965+0000] {processor.py:157} INFO - Started process (PID=337) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T20:57:28.965+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T20:57:28.967+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:57:28.967+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T20:57:28.971+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:57:28.970+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T20:57:28.972+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T20:57:28.982+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.020 seconds
[2023-12-29T20:57:59.311+0000] {processor.py:157} INFO - Started process (PID=345) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T20:57:59.312+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T20:57:59.315+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:57:59.315+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T20:57:59.323+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:57:59.320+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T20:57:59.323+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T20:57:59.336+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.029 seconds
[2023-12-29T20:58:29.698+0000] {processor.py:157} INFO - Started process (PID=353) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T20:58:29.699+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T20:58:29.701+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:58:29.700+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T20:58:29.708+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:58:29.707+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T20:58:29.710+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T20:58:29.720+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.023 seconds
[2023-12-29T20:59:00.109+0000] {processor.py:157} INFO - Started process (PID=361) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T20:59:00.111+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T20:59:00.112+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:59:00.112+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T20:59:00.118+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:59:00.117+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T20:59:00.118+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T20:59:00.128+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.021 seconds
[2023-12-29T20:59:30.560+0000] {processor.py:157} INFO - Started process (PID=369) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T20:59:30.562+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T20:59:30.566+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:59:30.566+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T20:59:30.574+0000] {logging_mixin.py:154} INFO - [2023-12-29T20:59:30.572+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T20:59:30.575+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T20:59:30.594+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.039 seconds
[2023-12-29T21:00:00.955+0000] {processor.py:157} INFO - Started process (PID=377) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T21:00:00.956+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T21:00:00.959+0000] {logging_mixin.py:154} INFO - [2023-12-29T21:00:00.958+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T21:00:00.964+0000] {logging_mixin.py:154} INFO - [2023-12-29T21:00:00.962+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T21:00:00.964+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T21:00:00.978+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.025 seconds
[2023-12-29T21:00:31.364+0000] {processor.py:157} INFO - Started process (PID=385) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T21:00:31.366+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T21:00:31.370+0000] {logging_mixin.py:154} INFO - [2023-12-29T21:00:31.370+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T21:00:31.377+0000] {logging_mixin.py:154} INFO - [2023-12-29T21:00:31.375+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T21:00:31.377+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T21:00:31.393+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.034 seconds
[2023-12-29T21:01:01.714+0000] {processor.py:157} INFO - Started process (PID=393) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T21:01:01.715+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T21:01:01.719+0000] {logging_mixin.py:154} INFO - [2023-12-29T21:01:01.718+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T21:01:01.729+0000] {logging_mixin.py:154} INFO - [2023-12-29T21:01:01.727+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T21:01:01.730+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T21:01:01.750+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.041 seconds
[2023-12-29T21:01:32.096+0000] {processor.py:157} INFO - Started process (PID=401) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T21:01:32.097+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T21:01:32.099+0000] {logging_mixin.py:154} INFO - [2023-12-29T21:01:32.098+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T21:01:32.103+0000] {logging_mixin.py:154} INFO - [2023-12-29T21:01:32.102+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T21:01:32.104+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T21:01:32.119+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.026 seconds
[2023-12-29T21:02:02.464+0000] {processor.py:157} INFO - Started process (PID=409) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T21:02:02.466+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T21:02:02.470+0000] {logging_mixin.py:154} INFO - [2023-12-29T21:02:02.469+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T21:02:02.478+0000] {logging_mixin.py:154} INFO - [2023-12-29T21:02:02.476+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T21:02:02.478+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T21:02:02.500+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.041 seconds
[2023-12-29T21:02:32.854+0000] {processor.py:157} INFO - Started process (PID=417) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T21:02:32.855+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T21:02:32.858+0000] {logging_mixin.py:154} INFO - [2023-12-29T21:02:32.858+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T21:02:32.863+0000] {logging_mixin.py:154} INFO - [2023-12-29T21:02:32.862+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T21:02:32.864+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T21:02:32.877+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.026 seconds
[2023-12-29T21:03:03.210+0000] {processor.py:157} INFO - Started process (PID=425) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T21:03:03.211+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T21:03:03.214+0000] {logging_mixin.py:154} INFO - [2023-12-29T21:03:03.213+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T21:03:03.220+0000] {logging_mixin.py:154} INFO - [2023-12-29T21:03:03.219+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T21:03:03.221+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T21:03:03.240+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.035 seconds
[2023-12-29T21:03:33.596+0000] {processor.py:157} INFO - Started process (PID=433) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T21:03:33.597+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T21:03:33.601+0000] {logging_mixin.py:154} INFO - [2023-12-29T21:03:33.600+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T21:03:33.608+0000] {logging_mixin.py:154} INFO - [2023-12-29T21:03:33.607+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T21:03:33.609+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T21:03:33.630+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.040 seconds
[2023-12-29T21:04:03.987+0000] {processor.py:157} INFO - Started process (PID=441) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T21:04:03.991+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T21:04:04.000+0000] {logging_mixin.py:154} INFO - [2023-12-29T21:04:04.000+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T21:04:04.012+0000] {logging_mixin.py:154} INFO - [2023-12-29T21:04:04.009+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T21:04:04.012+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T21:04:04.062+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.086 seconds
[2023-12-29T21:04:34.399+0000] {processor.py:157} INFO - Started process (PID=449) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T21:04:34.402+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T21:04:34.407+0000] {logging_mixin.py:154} INFO - [2023-12-29T21:04:34.406+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T21:04:34.415+0000] {logging_mixin.py:154} INFO - [2023-12-29T21:04:34.413+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T21:04:34.415+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T21:04:34.442+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.050 seconds
[2023-12-29T21:05:04.769+0000] {processor.py:157} INFO - Started process (PID=457) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T21:05:04.770+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T21:05:04.774+0000] {logging_mixin.py:154} INFO - [2023-12-29T21:05:04.773+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T21:05:04.781+0000] {logging_mixin.py:154} INFO - [2023-12-29T21:05:04.779+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T21:05:04.782+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T21:05:04.803+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.039 seconds
[2023-12-29T21:05:35.205+0000] {processor.py:157} INFO - Started process (PID=465) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T21:05:35.207+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T21:05:35.212+0000] {logging_mixin.py:154} INFO - [2023-12-29T21:05:35.212+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T21:05:35.221+0000] {logging_mixin.py:154} INFO - [2023-12-29T21:05:35.219+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T21:05:35.221+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T21:05:35.240+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2023-12-29T21:06:05.570+0000] {processor.py:157} INFO - Started process (PID=473) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T21:06:05.571+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T21:06:05.574+0000] {logging_mixin.py:154} INFO - [2023-12-29T21:06:05.574+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T21:06:05.582+0000] {logging_mixin.py:154} INFO - [2023-12-29T21:06:05.580+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T21:06:05.582+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T21:06:05.604+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.040 seconds
[2023-12-29T21:06:36.010+0000] {processor.py:157} INFO - Started process (PID=481) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T21:06:36.011+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T21:06:36.015+0000] {logging_mixin.py:154} INFO - [2023-12-29T21:06:36.015+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T21:06:36.023+0000] {logging_mixin.py:154} INFO - [2023-12-29T21:06:36.021+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T21:06:36.024+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T21:06:36.044+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.039 seconds
[2023-12-29T21:07:06.431+0000] {processor.py:157} INFO - Started process (PID=489) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T21:07:06.435+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T21:07:06.444+0000] {logging_mixin.py:154} INFO - [2023-12-29T21:07:06.443+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T21:07:06.463+0000] {logging_mixin.py:154} INFO - [2023-12-29T21:07:06.460+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T21:07:06.464+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T21:07:06.507+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.087 seconds
[2023-12-29T22:12:58.449+0000] {processor.py:157} INFO - Started process (PID=497) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T22:12:58.451+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T22:12:58.455+0000] {logging_mixin.py:154} INFO - [2023-12-29T22:12:58.455+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T22:12:58.462+0000] {logging_mixin.py:154} INFO - [2023-12-29T22:12:58.460+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T22:12:58.466+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T22:12:58.482+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.041 seconds
[2023-12-29T23:24:16.121+0000] {processor.py:157} INFO - Started process (PID=505) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T23:24:16.122+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T23:24:16.125+0000] {logging_mixin.py:154} INFO - [2023-12-29T23:24:16.125+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T23:24:16.130+0000] {logging_mixin.py:154} INFO - [2023-12-29T23:24:16.129+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T23:24:16.131+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T23:24:16.143+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.026 seconds
[2023-12-29T23:56:08.250+0000] {processor.py:157} INFO - Started process (PID=513) to work on /opt/airflow/dags/test_dag.py
[2023-12-29T23:56:08.251+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-12-29T23:56:08.256+0000] {logging_mixin.py:154} INFO - [2023-12-29T23:56:08.255+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-12-29T23:56:08.263+0000] {logging_mixin.py:154} INFO - [2023-12-29T23:56:08.261+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.decorators import dags, task
ImportError: cannot import name 'dags' from 'airflow.decorators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/__init__.py)
[2023-12-29T23:56:08.263+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-12-29T23:56:08.281+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.035 seconds
