[2024-01-31T17:38:39.513+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: your_redshift_dag.run_redshift_query scheduled__2023-12-02T00:00:00+00:00 [queued]>
[2024-01-31T17:38:39.520+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: your_redshift_dag.run_redshift_query scheduled__2023-12-02T00:00:00+00:00 [queued]>
[2024-01-31T17:38:39.520+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-01-31T17:38:39.529+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): run_redshift_query> on 2023-12-02 00:00:00+00:00
[2024-01-31T17:38:39.532+0000] {standard_task_runner.py:57} INFO - Started process 11619 to run task
[2024-01-31T17:38:39.537+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'your_redshift_dag', 'run_redshift_query', 'scheduled__2023-12-02T00:00:00+00:00', '--job-id', '1054', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmp6t7hibro']
[2024-01-31T17:38:39.538+0000] {standard_task_runner.py:85} INFO - Job 1054: Subtask run_redshift_query
[2024-01-31T17:38:39.575+0000] {task_command.py:416} INFO - Running <TaskInstance: your_redshift_dag.run_redshift_query scheduled__2023-12-02T00:00:00+00:00 [running]> on host d6d47e6adee9
[2024-01-31T17:38:39.623+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_owner' AIRFLOW_CTX_DAG_ID='your_redshift_dag' AIRFLOW_CTX_TASK_ID='run_redshift_query' AIRFLOW_CTX_EXECUTION_DATE='2023-12-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-02T00:00:00+00:00'
[2024-01-31T17:38:39.945+0000] {base.py:73} INFO - Using connection ID 'redshift_conn' for task execution.
[2024-01-31T17:38:39.947+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_dag.py", line 30, in execute_redshift_query
    result = hook.get_pandas_df(sql=redshift_query)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 218, in get_pandas_df
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 155, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "marina-dev.cokvj8a8m59a.us-west-2.redshift.amazonaws.com:5439" to address: Name or service not known

[2024-01-31T17:38:39.953+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=your_redshift_dag, task_id=run_redshift_query, execution_date=20231202T000000, start_date=20240131T173839, end_date=20240131T173839
[2024-01-31T17:38:39.960+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1054 for task run_redshift_query (could not translate host name "marina-dev.cokvj8a8m59a.us-west-2.redshift.amazonaws.com:5439" to address: Name or service not known
; 11619)
[2024-01-31T17:38:39.999+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-31T17:38:40.015+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
